In [3]:
from tensorflow.keras.preprocessing.text  import one_hot
import pandas as pd

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
## we need to define voacbulary size
voc_size = 10000


In [11]:
### one hot representation
one_hot_represent=[one_hot(words, voc_size) for words in sent]
one_hot_represent


[[6860, 7921, 9269, 838],
 [6860, 7921, 9269, 2200],
 [6860, 5906, 9269, 2280],
 [8208, 3880, 115, 3712, 6131],
 [8208, 3880, 115, 3712, 1700],
 [6018, 6860, 6936, 9269, 2070],
 [7409, 1665, 8576, 3712]]

In [ ]:
## word embeding representation
from tensorflow.keras.layers import Embedding
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [16]:
from tensorflow.keras.utils import pad_sequences
import numpy as np

In [18]:
sent_length =8
embedded_docs = pad_sequences(one_hot_represent, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6860 7921 9269  838]
 [   0    0    0    0 6860 7921 9269 2200]
 [   0    0    0    0 6860 5906 9269 2280]
 [   0    0    0 8208 3880  115 3712 6131]
 [   0    0    0 8208 3880  115 3712 1700]
 [   0    0    0 6018 6860 6936 9269 2070]
 [   0    0    0    0 7409 1665 8576 3712]]


In [19]:
## feature representation
dim=10

In [20]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [23]:
embedded_docs[0]

array([   0,    0,    0,    0, 6860, 7921, 9269,  838])

In [22]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 311ms/step


array([[[-0.00228723,  0.02553045, -0.03410979,  0.03899897,
          0.04717613, -0.04497708,  0.0175528 ,  0.03629893,
          0.00750656,  0.02541867],
        [-0.00228723,  0.02553045, -0.03410979,  0.03899897,
          0.04717613, -0.04497708,  0.0175528 ,  0.03629893,
          0.00750656,  0.02541867],
        [-0.00228723,  0.02553045, -0.03410979,  0.03899897,
          0.04717613, -0.04497708,  0.0175528 ,  0.03629893,
          0.00750656,  0.02541867],
        [-0.00228723,  0.02553045, -0.03410979,  0.03899897,
          0.04717613, -0.04497708,  0.0175528 ,  0.03629893,
          0.00750656,  0.02541867],
        [-0.02671734,  0.00422124,  0.04914837,  0.01032462,
         -0.01583865,  0.00034564,  0.04684694,  0.01075325,
          0.02177567, -0.00493956],
        [-0.0128757 ,  0.04506929, -0.04214565, -0.04049306,
          0.02730793,  0.04671481,  0.03704654,  0.02200259,
         -0.03406346, -0.03552204],
        [ 0.04870659, -0.04415784, -0.04304131, -0.0